name: m3u_parser_nullsafe
description: m3u parser
version: 1.0.3
homepage: https://github.com/xxzj990/m3u_parser

environment:
  sdk: '>=2.18.6 <3.0.0'

dev_dependencies:
  pedantic: ^1.8.0
  test: ^1.6.0
